data_ingestion:
  test_size: 0.20
  random_state: 42
  source_data_path: 'main_data/spam.csv'
  save_dir: "./data"

data_preprocessing:
  text_column: "text"
  target_column: "label"
  train_data_path: "./data/raw/train.csv"
  test_data_path: "./data/raw/test.csv"
  output_path: "./data/processed"

feature_engineer_params:
  text_column: "text"
  target_column: "label"
  
  # Input paths (from preprocessing)
  train_data_path: "./data/processed/train_processed.csv"
  test_data_path: "./data/processed/test_processed.csv"
  
  # Output paths (feature vectors)
  x_train_data_path: "./data/final/x_train.csv"
  x_test_data_path: "./data/final/x_test.csv"
  y_train_data_path: "./data/final/y_train.csv"
  y_test_data_path: "./data/final/y_test.csv"
  word2vec_model_path: "./models/word2vec.model"  
  
  # Word2Vec hyperparameters
  word2vec_params:
    vector_size: 100
    min_count: 1
    window: 5
    workers: 4
    sg: 1  
    epochs: 20


## model training params
model_training:
  x_train_data_path: "./data/final/x_train.csv"
  y_train_data_path: "./data/final/y_train.csv"
  rf_model_path: "./models/rf_model.pkl"

  ## RandomForestClassifier params
  rf_params:
    n_estimators: 100
    max_depth: 7
    criterion: 'gini'
    class_weight: 'balanced'
    n_jobs: -1
    random_state: 42

model_evaluation:
  x_test_data_path: "./data/final/x_test.csv"
  y_test_data_path: "./data/final/y_test.csv"
  rf_model_path: "./models/rf_model.pkl"

  evaluation_metric_path: "./reports/metrics.json"
